# Generated by Django 3.0.1 on 2019-12-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=50)),
                ('e_number', models.IntegerField()),
                ('e_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
